#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLINQ_Usage_CRUD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="vizagdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblStudent(tblStudent instance);
    partial void UpdatetblStudent(tblStudent instance);
    partial void DeletetblStudent(tblStudent instance);
    partial void InserttblJob(tblJob instance);
    partial void UpdatetblJob(tblJob instance);
    partial void DeletetblJob(tblJob instance);
    partial void Inserttbl_location(tbl_location instance);
    partial void Updatetbl_location(tbl_location instance);
    partial void Deletetbl_location(tbl_location instance);
    partial void Inserttbl_Dept(tbl_Dept instance);
    partial void Updatetbl_Dept(tbl_Dept instance);
    partial void Deletetbl_Dept(tbl_Dept instance);
    partial void Inserttbl_Emp(tbl_Emp instance);
    partial void Updatetbl_Emp(tbl_Emp instance);
    partial void Deletetbl_Emp(tbl_Emp instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblStudent> tblStudents
		{
			get
			{
				return this.GetTable<tblStudent>();
			}
		}
		
		public System.Data.Linq.Table<tblJob> tblJobs
		{
			get
			{
				return this.GetTable<tblJob>();
			}
		}
		
		public System.Data.Linq.Table<tbl_location> tbl_locations
		{
			get
			{
				return this.GetTable<tbl_location>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Dept> tbl_Depts
		{
			get
			{
				return this.GetTable<tbl_Dept>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Emp> tbl_Emps
		{
			get
			{
				return this.GetTable<tbl_Emp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
	public partial class tblStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studId;
		
		private string _studName;
		
		private string _studMobile;
		
		private System.Nullable<int> _studAge;
		
		private System.Nullable<char> _studGender;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudIdChanging(int value);
    partial void OnstudIdChanged();
    partial void OnstudNameChanging(string value);
    partial void OnstudNameChanged();
    partial void OnstudMobileChanging(string value);
    partial void OnstudMobileChanged();
    partial void OnstudAgeChanging(System.Nullable<int> value);
    partial void OnstudAgeChanged();
    partial void OnstudGenderChanging(System.Nullable<char> value);
    partial void OnstudGenderChanged();
    #endregion
		
		public tblStudent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int studId
		{
			get
			{
				return this._studId;
			}
			set
			{
				if ((this._studId != value))
				{
					this.OnstudIdChanging(value);
					this.SendPropertyChanging();
					this._studId = value;
					this.SendPropertyChanged("studId");
					this.OnstudIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studName", DbType="VarChar(50)")]
		public string studName
		{
			get
			{
				return this._studName;
			}
			set
			{
				if ((this._studName != value))
				{
					this.OnstudNameChanging(value);
					this.SendPropertyChanging();
					this._studName = value;
					this.SendPropertyChanged("studName");
					this.OnstudNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studMobile", DbType="VarChar(10)")]
		public string studMobile
		{
			get
			{
				return this._studMobile;
			}
			set
			{
				if ((this._studMobile != value))
				{
					this.OnstudMobileChanging(value);
					this.SendPropertyChanging();
					this._studMobile = value;
					this.SendPropertyChanged("studMobile");
					this.OnstudMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studAge", DbType="Int")]
		public System.Nullable<int> studAge
		{
			get
			{
				return this._studAge;
			}
			set
			{
				if ((this._studAge != value))
				{
					this.OnstudAgeChanging(value);
					this.SendPropertyChanging();
					this._studAge = value;
					this.SendPropertyChanged("studAge");
					this.OnstudAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studGender", DbType="Char(1)")]
		public System.Nullable<char> studGender
		{
			get
			{
				return this._studGender;
			}
			set
			{
				if ((this._studGender != value))
				{
					this.OnstudGenderChanging(value);
					this.SendPropertyChanging();
					this._studGender = value;
					this.SendPropertyChanged("studGender");
					this.OnstudGenderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblJob")]
	public partial class tblJob : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _jcode;
		
		private string _jname;
		
		private EntitySet<tbl_Emp> _tbl_Emps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnjcodeChanging(int value);
    partial void OnjcodeChanged();
    partial void OnjnameChanging(string value);
    partial void OnjnameChanged();
    #endregion
		
		public tblJob()
		{
			this._tbl_Emps = new EntitySet<tbl_Emp>(new Action<tbl_Emp>(this.attach_tbl_Emps), new Action<tbl_Emp>(this.detach_tbl_Emps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jcode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int jcode
		{
			get
			{
				return this._jcode;
			}
			set
			{
				if ((this._jcode != value))
				{
					this.OnjcodeChanging(value);
					this.SendPropertyChanging();
					this._jcode = value;
					this.SendPropertyChanged("jcode");
					this.OnjcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jname
		{
			get
			{
				return this._jname;
			}
			set
			{
				if ((this._jname != value))
				{
					this.OnjnameChanging(value);
					this.SendPropertyChanging();
					this._jname = value;
					this.SendPropertyChanged("jname");
					this.OnjnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblJob_tbl_Emp", Storage="_tbl_Emps", ThisKey="jcode", OtherKey="jcode")]
		public EntitySet<tbl_Emp> tbl_Emps
		{
			get
			{
				return this._tbl_Emps;
			}
			set
			{
				this._tbl_Emps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Emps(tbl_Emp entity)
		{
			this.SendPropertyChanging();
			entity.tblJob = this;
		}
		
		private void detach_tbl_Emps(tbl_Emp entity)
		{
			this.SendPropertyChanging();
			entity.tblJob = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_location")]
	public partial class tbl_location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loccode;
		
		private string _locname;
		
		private EntitySet<tbl_Dept> _tbl_Depts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnloccodeChanging(int value);
    partial void OnloccodeChanged();
    partial void OnlocnameChanging(string value);
    partial void OnlocnameChanged();
    #endregion
		
		public tbl_location()
		{
			this._tbl_Depts = new EntitySet<tbl_Dept>(new Action<tbl_Dept>(this.attach_tbl_Depts), new Action<tbl_Dept>(this.detach_tbl_Depts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loccode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int loccode
		{
			get
			{
				return this._loccode;
			}
			set
			{
				if ((this._loccode != value))
				{
					this.OnloccodeChanging(value);
					this.SendPropertyChanging();
					this._loccode = value;
					this.SendPropertyChanged("loccode");
					this.OnloccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locname", DbType="VarChar(50)")]
		public string locname
		{
			get
			{
				return this._locname;
			}
			set
			{
				if ((this._locname != value))
				{
					this.OnlocnameChanging(value);
					this.SendPropertyChanging();
					this._locname = value;
					this.SendPropertyChanged("locname");
					this.OnlocnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_location_tbl_Dept", Storage="_tbl_Depts", ThisKey="loccode", OtherKey="lcode")]
		public EntitySet<tbl_Dept> tbl_Depts
		{
			get
			{
				return this._tbl_Depts;
			}
			set
			{
				this._tbl_Depts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Depts(tbl_Dept entity)
		{
			this.SendPropertyChanging();
			entity.tbl_location = this;
		}
		
		private void detach_tbl_Depts(tbl_Dept entity)
		{
			this.SendPropertyChanging();
			entity.tbl_location = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Dept")]
	public partial class tbl_Dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _deptno;
		
		private string _dname;
		
		private System.Nullable<int> _lcode;
		
		private EntitySet<tbl_Emp> _tbl_Emps;
		
		private EntityRef<tbl_location> _tbl_location;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndeptnoChanging(int value);
    partial void OndeptnoChanged();
    partial void OndnameChanging(string value);
    partial void OndnameChanged();
    partial void OnlcodeChanging(System.Nullable<int> value);
    partial void OnlcodeChanged();
    #endregion
		
		public tbl_Dept()
		{
			this._tbl_Emps = new EntitySet<tbl_Emp>(new Action<tbl_Emp>(this.attach_tbl_Emps), new Action<tbl_Emp>(this.detach_tbl_Emps));
			this._tbl_location = default(EntityRef<tbl_location>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int deptno
		{
			get
			{
				return this._deptno;
			}
			set
			{
				if ((this._deptno != value))
				{
					this.OndeptnoChanging(value);
					this.SendPropertyChanging();
					this._deptno = value;
					this.SendPropertyChanged("deptno");
					this.OndeptnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dname", DbType="VarChar(15)")]
		public string dname
		{
			get
			{
				return this._dname;
			}
			set
			{
				if ((this._dname != value))
				{
					this.OndnameChanging(value);
					this.SendPropertyChanging();
					this._dname = value;
					this.SendPropertyChanged("dname");
					this.OndnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lcode", DbType="Int")]
		public System.Nullable<int> lcode
		{
			get
			{
				return this._lcode;
			}
			set
			{
				if ((this._lcode != value))
				{
					if (this._tbl_location.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlcodeChanging(value);
					this.SendPropertyChanging();
					this._lcode = value;
					this.SendPropertyChanged("lcode");
					this.OnlcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dept_tbl_Emp", Storage="_tbl_Emps", ThisKey="deptno", OtherKey="DEPTNO")]
		public EntitySet<tbl_Emp> tbl_Emps
		{
			get
			{
				return this._tbl_Emps;
			}
			set
			{
				this._tbl_Emps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_location_tbl_Dept", Storage="_tbl_location", ThisKey="lcode", OtherKey="loccode", IsForeignKey=true)]
		public tbl_location tbl_location
		{
			get
			{
				return this._tbl_location.Entity;
			}
			set
			{
				tbl_location previousValue = this._tbl_location.Entity;
				if (((previousValue != value) 
							|| (this._tbl_location.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_location.Entity = null;
						previousValue.tbl_Depts.Remove(this);
					}
					this._tbl_location.Entity = value;
					if ((value != null))
					{
						value.tbl_Depts.Add(this);
						this._lcode = value.loccode;
					}
					else
					{
						this._lcode = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_location");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Emps(tbl_Emp entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dept = this;
		}
		
		private void detach_tbl_Emps(tbl_Emp entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dept = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Emp")]
	public partial class tbl_Emp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _empno;
		
		private string _ename;
		
		private System.Nullable<int> _jcode;
		
		private System.Nullable<int> _mgrno;
		
		private System.Nullable<System.DateTime> _hiredate;
		
		private System.Nullable<int> _salary;
		
		private System.Nullable<double> _commission;
		
		private System.Nullable<int> _DEPTNO;
		
		private EntityRef<tbl_Dept> _tbl_Dept;
		
		private EntityRef<tblJob> _tblJob;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnempnoChanging(int value);
    partial void OnempnoChanged();
    partial void OnenameChanging(string value);
    partial void OnenameChanged();
    partial void OnjcodeChanging(System.Nullable<int> value);
    partial void OnjcodeChanged();
    partial void OnmgrnoChanging(System.Nullable<int> value);
    partial void OnmgrnoChanged();
    partial void OnhiredateChanging(System.Nullable<System.DateTime> value);
    partial void OnhiredateChanged();
    partial void OnsalaryChanging(System.Nullable<int> value);
    partial void OnsalaryChanged();
    partial void OncommissionChanging(System.Nullable<double> value);
    partial void OncommissionChanged();
    partial void OnDEPTNOChanging(System.Nullable<int> value);
    partial void OnDEPTNOChanged();
    #endregion
		
		public tbl_Emp()
		{
			this._tbl_Dept = default(EntityRef<tbl_Dept>);
			this._tblJob = default(EntityRef<tblJob>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int empno
		{
			get
			{
				return this._empno;
			}
			set
			{
				if ((this._empno != value))
				{
					this.OnempnoChanging(value);
					this.SendPropertyChanging();
					this._empno = value;
					this.SendPropertyChanged("empno");
					this.OnempnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ename", DbType="VarChar(50)")]
		public string ename
		{
			get
			{
				return this._ename;
			}
			set
			{
				if ((this._ename != value))
				{
					this.OnenameChanging(value);
					this.SendPropertyChanging();
					this._ename = value;
					this.SendPropertyChanged("ename");
					this.OnenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jcode", DbType="Int")]
		public System.Nullable<int> jcode
		{
			get
			{
				return this._jcode;
			}
			set
			{
				if ((this._jcode != value))
				{
					if (this._tblJob.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjcodeChanging(value);
					this.SendPropertyChanging();
					this._jcode = value;
					this.SendPropertyChanged("jcode");
					this.OnjcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgrno", DbType="Int")]
		public System.Nullable<int> mgrno
		{
			get
			{
				return this._mgrno;
			}
			set
			{
				if ((this._mgrno != value))
				{
					this.OnmgrnoChanging(value);
					this.SendPropertyChanging();
					this._mgrno = value;
					this.SendPropertyChanged("mgrno");
					this.OnmgrnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiredate", DbType="Date")]
		public System.Nullable<System.DateTime> hiredate
		{
			get
			{
				return this._hiredate;
			}
			set
			{
				if ((this._hiredate != value))
				{
					this.OnhiredateChanging(value);
					this.SendPropertyChanging();
					this._hiredate = value;
					this.SendPropertyChanged("hiredate");
					this.OnhiredateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Int")]
		public System.Nullable<int> salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commission", DbType="Float")]
		public System.Nullable<double> commission
		{
			get
			{
				return this._commission;
			}
			set
			{
				if ((this._commission != value))
				{
					this.OncommissionChanging(value);
					this.SendPropertyChanging();
					this._commission = value;
					this.SendPropertyChanged("commission");
					this.OncommissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPTNO", DbType="Int")]
		public System.Nullable<int> DEPTNO
		{
			get
			{
				return this._DEPTNO;
			}
			set
			{
				if ((this._DEPTNO != value))
				{
					if (this._tbl_Dept.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDEPTNOChanging(value);
					this.SendPropertyChanging();
					this._DEPTNO = value;
					this.SendPropertyChanged("DEPTNO");
					this.OnDEPTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dept_tbl_Emp", Storage="_tbl_Dept", ThisKey="DEPTNO", OtherKey="deptno", IsForeignKey=true)]
		public tbl_Dept tbl_Dept
		{
			get
			{
				return this._tbl_Dept.Entity;
			}
			set
			{
				tbl_Dept previousValue = this._tbl_Dept.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Dept.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Dept.Entity = null;
						previousValue.tbl_Emps.Remove(this);
					}
					this._tbl_Dept.Entity = value;
					if ((value != null))
					{
						value.tbl_Emps.Add(this);
						this._DEPTNO = value.deptno;
					}
					else
					{
						this._DEPTNO = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Dept");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblJob_tbl_Emp", Storage="_tblJob", ThisKey="jcode", OtherKey="jcode", IsForeignKey=true)]
		public tblJob tblJob
		{
			get
			{
				return this._tblJob.Entity;
			}
			set
			{
				tblJob previousValue = this._tblJob.Entity;
				if (((previousValue != value) 
							|| (this._tblJob.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblJob.Entity = null;
						previousValue.tbl_Emps.Remove(this);
					}
					this._tblJob.Entity = value;
					if ((value != null))
					{
						value.tbl_Emps.Add(this);
						this._jcode = value.jcode;
					}
					else
					{
						this._jcode = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblJob");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
